### ISSUE TITLE
On-Demand Service stops tracking uptime after the restart

### ISSUE THREAD

**Issue by binlab** [acouvreur/traefik-ondemand-service#28]
I got a similar issue with [traefik-ondemand-plugin#23](https://github.com/acouvreur/traefik-ondemand-plugin/issues/23). 
The issue happens when `traefik-ondemand-service` was crashed and reloaded or just redeployed in time when _services were UP_. After it happened, `traefik-ondemand-service` stops tracking uptime of all services which should be as expected. 
Does it possible to add start initialization for tracking configured in timeouts in each service?

**Comment by acouvreur** [comment]
The service traks the service in memory, which means everything is lost upon restart.

Do you think that it should be kept in a persistent storage ?

If so, how would you implement such updates, because the updates are as frequent as there is an http call.

I think it should be a sync to file every 5s or so. I might implement that in a future release, what do you think?

**Comment by Nastaliss** [comment]
Hey @acouvreur . 
We discussed this matter today, I think this would be a great improvement ! 
Sometimes the container restarts and the service looses its state. 

I think using a periodic write to file would make it scale better than a write every HTTP request. It would also make the implementation easier.

Maybe we could make the sync interval configuratble via an env variable.

**Comment by acouvreur** [comment]
You can try it out now, take a look at #30

**Comment by acouvreur** [comment]
Thanks for the feedback, can you provide more info about the context of this log ? 
`fatal error: concurrent map iteration and map write,`

It's probably because of me though :laughing: I'll check my fork of the lib https://github.com/acouvreur/tinykv

I think exposing prometheus metrics is a good idea, it can be directly exposed through this service.

**Comment by Nastaliss** [comment]
Sure, here are the end of the logs before a restart :
[ods-error.log](https://github.com/acouvreur/traefik-ondemand-service/files/8676258/ods-error.log)

**Comment by acouvreur** [comment]
Pushed a fix on beta
https://github.com/acouvreur/traefik-ondemand-service/commit/96547ce4bf2079df6831c9972144818532fe0fd7

https://github.com/acouvreur/tinykv/commit/45fc921a4a8313a075e6a2559f464fce4f2f1816

**Comment by Nastaliss** [comment]
Upgrading to `v1.8.0-beta.2` then ! 
I'll let you know if I encounter other issues.
